### ISSUE TITLE
Erreur HTML sur le bouton de copie

### ISSUE THREAD

**Issue by NumEricR** [Darklg/CSSLisible#81]
Hello,

Une petite erreur HTML s'est glissée au niveau du [bouton "Copier ce code"](https://github.com/Darklg/CSSLisible/blob/master/inc/tpl/submit.php#L13) : un ";" apparait après le "data-success-msg".
```
<button id="copy_button" class="go_clean_css hide" data-success-msg="Code copié"; data-clipboard-target="clean_css">Copier ce code</button>
```

**Comment by Darklg** [comment]
Bien vu, merci :)
