### ISSUE TITLE
Option "un sélecteur par ligne" KO

### ISSUE THREAD

**Issue by NumEricR** [Darklg/CSSLisible#85]
Avec 0c3ab7fa8d4e30e21dbe1f19d1bdf91162e5fb0a si je coche l'option "Un sélecteur par ligne" et que j'utilise le code suivant,
```
.test {
p {
    color: white;
}
}
```
... j'obtiens ce résultat un peu étrange :(
```
.test {    p {    color: white;}
}
```

**Comment by NumEricR** [comment]
Et avec 
```
.odd,.even {
  color: black;
}
```
Je récupère :
```
.odd, .even {    color: black;}
```

**Comment by Darklg** [comment]
Etrange, ça doit dater d'avant, je regarde, merci !

**Comment by NumEricR** [comment]
Sur csslisible.com, j'ai le même comportement pour l'exemple ```.odd,.even```

**Comment by Darklg** [comment]
oui, c'est sûr qu'il y a un moment où ça a cassé avant, je vais mettre en place des tests unitaires sinon ça va plus être possible :)
